//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WallStreetGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public long Id { get; set; }
        public string FullName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public byte[] Image { get; set; }
        public decimal Money { get; set; }
        public string Sex { get; set; }
        public long Gold { get; set; }
        public long Petrol { get; set; }
        public long Antiques { get; set; }
        public long Bitcoin { get; set; }
        public long Shares { get; set; }
        public long Technologies { get; set; }
        public decimal Loan { get; set; }
    }
}
